# Generated by Django 4.2 on 2025-11-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerprofile',
            name='company_name',
            field=models.CharField(default='My Company', max_length=200),
        ),
    ]
