# Generated by Django 4.2 on 2025-11-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_organizerprofile_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizerprofile',
            old_name='company_registration',
            new_name='organizer_id',
        ),
        migrations.RenameField(
            model_name='touristprofile',
            old_name='nationality',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='touristprofile',
            old_name='emergency_contact',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='company_name',
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='department',
            field=models.CharField(default='CSE Department', max_length=200),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('organizer', 'Tour Organizer'), ('developer', 'Developer')], default='tourist', max_length=20),
        ),
    ]
