# Generated by Django 4.2 on 2025-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_payment_uapdepartment_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_number',
            field=models.CharField(blank=True, help_text='bKash/Nagad/Rocket number', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer')], max_length=20),
        ),
    ]
