# Generated by Django 4.2 on 2025-11-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_booking_payment_number_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
