# Generated by Django 4.2 on 2025-11-15 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0004_tour_qr_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('tour', 'tourist')},
        ),
    ]
